# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choiceText', models.TextField(max_length=200, verbose_name='\u95ee\u9898')),
                ('choiceAnswer', models.TextField(blank=True, default='', max_length=1000, verbose_name='\u95ee\u7b54\u7ed3\u679c')),
                ('choiceVote', models.IntegerField(blank=True, default=0, verbose_name='\u6295\u7968\u7ed3\u679c')),
                ('whoVote', models.CharField(blank=True, default='', max_length=200, verbose_name='\u6295\u7968\u4eba')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20, verbose_name='\u53d1\u8d77\u4eba')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('alreadyVote', models.CharField(blank=True, default='', max_length=1000, verbose_name='\u5df2\u53c2\u4e0e\u4eba\u5458')),
                ('choose', models.CharField(choices=[('\u6295\u7968', '\u6295\u7968'), ('\u95ee\u7b54', '\u95ee\u7b54'), ('\u516c\u544a', '\u516c\u544a')], default='\u6295\u7968', max_length=15, verbose_name='\u7c7b\u578b')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Question'),
        ),
    ]
