# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-08 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0006_auto_20181006_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=20, verbose_name='\u5458\u5de5\u59d3\u540d'),
        ),
    ]
