# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-28 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, verbose_name='IP')),
                ('location', models.CharField(max_length=50, verbose_name='\u4f4d\u7f6e')),
                ('status', models.BooleanField(default=False, verbose_name='\u72b6\u6001')),
                ('admin', models.CharField(max_length=20, verbose_name='\u7ba1\u7406\u5458')),
                ('user', models.CharField(blank=True, max_length=20, verbose_name='\u4f7f\u7528\u8005')),
            ],
            options={
                'ordering': ['ip'],
            },
        ),
    ]
