# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, verbose_name='IP')),
                ('location', models.CharField(max_length=50, verbose_name='\u4f4d\u7f6e')),
                ('admin', models.CharField(max_length=20, verbose_name='\u7ba1\u7406\u5458')),
                ('user', models.CharField(blank=True, max_length=20, verbose_name='\u4f7f\u7528\u8005')),
                ('information', models.TextField(blank=True, max_length=100, verbose_name='\u8bbe\u5907\u4fe1\u606f')),
                ('expiration', models.DateField(default=django.utils.timezone.now, verbose_name='\u8fc7\u671f\u65f6\u95f4')),
                ('status', models.CharField(choices=[('\u672a\u4f7f\u7528', '\u672a\u4f7f\u7528'), ('\u5f85\u6279\u51c6', '\u5f85\u6279\u51c6'), ('\u4f7f\u7528\u4e2d', '\u4f7f\u7528\u4e2d')], default='\u672a\u4f7f\u7528', max_length=10, verbose_name='\u72b6\u6001')),
            ],
            options={
                'ordering': ['-status'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='\u65e5\u671f')),
                ('handler', models.CharField(max_length=20, verbose_name='\u64cd\u4f5c\u8005')),
                ('content', models.CharField(max_length=100, verbose_name='\u5185\u5bb9')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
