# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-06 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('\u672a\u4f7f\u7528', '\u672a\u4f7f\u7528'), ('\u5f85\u6279\u51c6', '\u5f85\u6279\u51c6'), ('\u4f7f\u7528\u4e2d', '\u4f7f\u7528\u4e2d')], default='\u672a\u4f7f\u7528', max_length=10, verbose_name='\u72b6\u6001'),
        ),
    ]
