# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-06 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stable', '0002_auto_20181006_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='information',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u8bbe\u5907\u4fe1\u606f'),
        ),
    ]
