# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-08 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stable', '0003_device_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='information',
            field=models.TextField(blank=True, max_length=100, verbose_name='\u8bbe\u5907\u4fe1\u606f'),
        ),
    ]
